version: '3.8'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:latest
    ports:
      - "8080:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db_test:5432/progresoft
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: postgres_db_test
    environment:
      POSTGRES_DB: progresoft
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
